# Generated by Django 6.0.3 on 2026-03-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Full learning content shown after quest completion.'),
        ),
    ]
