# Generated by Django 6.0.3 on 2026-03-16 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_activitylog_skillxp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocks', to='quests.quest'),
        ),
        migrations.AddField(
            model_name='quest',
            name='quest_type',
            field=models.CharField(choices=[('learning', 'Learning Quest'), ('coding', 'Coding Quest'), ('quiz', 'Quiz Quest'), ('project', 'Project Quest'), ('boss', 'Boss Quest')], default='learning', max_length=10),
        ),
        migrations.CreateModel(
            name='QuestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('step_type', models.CharField(choices=[('learning', 'Learning'), ('coding', 'Coding'), ('quiz', 'Quiz')], default='learning', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Learning text, code prompt, or quiz question.')),
                ('correct_answer', models.TextField(blank=True, help_text='For quiz steps: the expected answer (case-insensitive match).')),
                ('xp_reward', models.IntegerField(default=20)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='quests.quest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('text', models.TextField()),
                ('xp_cost', models.IntegerField(default=5)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='quests.queststep')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='quests.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to=settings.AUTH_USER_MODEL)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quests.queststep')),
            ],
            options={
                'unique_together': {('user', 'quest')},
            },
        ),
        migrations.CreateModel(
            name='StepSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('github_link', models.URLField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quests.queststep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'step')},
            },
        ),
        migrations.CreateModel(
            name='UnlockedHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='quests.questhint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_hints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hint')},
            },
        ),
    ]
