import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'questlearn.settings')
django.setup()

from quests.models import Quest

content_map = {
    'Build your first HTML page': (
        "## What is HTML?\n"
        "HTML (HyperText Markup Language) is the skeleton of every webpage.\n\n"
        "## Core Tags\n"
        "- `<!DOCTYPE html>` — declares HTML5\n"
        "- `<html>` — root element\n"
        "- `<head>` — metadata (title, charset)\n"
        "- `<body>` — visible content\n\n"
        "## Your First Page\n"
        "```html\n"
        "<!DOCTYPE html>\n"
        "<html lang='en'>\n"
        "<head>\n"
        "  <meta charset='UTF-8'>\n"
        "  <title>My First Page</title>\n"
        "</head>\n"
        "<body>\n"
        "  <h1>Hello, World!</h1>\n"
        "  <p>This is my first HTML page.</p>\n"
        "  <ul>\n"
        "    <li>Item one</li>\n"
        "    <li>Item two</li>\n"
        "  </ul>\n"
        "</body>\n"
        "</html>\n"
        "```\n\n"
        "## Key Takeaways\n"
        "- Tags wrap content: `<tag>content</tag>`\n"
        "- Headings: `<h1>` (biggest) to `<h6>` (smallest)\n"
        "- `<p>` paragraphs, `<ul>`/`<ol>` lists, `<a>` links"
    ),
    'Style a page with CSS': (
        "## What is CSS?\n"
        "CSS (Cascading Style Sheets) controls how HTML looks — colors, fonts, spacing, layout.\n\n"
        "## Three Ways to Add CSS\n"
        "1. Inline: `<p style='color:red'>`\n"
        "2. Internal: `<style>` tag in `<head>`\n"
        "3. External: separate `.css` file (recommended)\n\n"
        "## Selectors\n"
        "```css\n"
        "h1 { color: #6366f1; font-size: 2rem; }\n"
        ".card { background: #1e1e3f; border-radius: 12px; padding: 1rem; }\n"
        "#hero { text-align: center; }\n"
        "```\n\n"
        "## Box Model\n"
        "Every element: content → padding → border → margin\n\n"
        "```css\n"
        ".box {\n"
        "  padding: 16px;\n"
        "  border: 1px solid #ccc;\n"
        "  margin: 8px;\n"
        "}\n"
        "```\n\n"
        "## Key Takeaways\n"
        "- Classes for reusable styles, IDs for unique elements\n"
        "- `display: flex` is your best friend for layouts\n"
        "- Link CSS in `<head>`: `<link rel='stylesheet' href='style.css'>`"
    ),
    'Add JavaScript interactivity': (
        "## What is JavaScript?\n"
        "JS makes pages dynamic — responding to clicks, updating content, validating forms.\n\n"
        "## Selecting Elements\n"
        "```js\n"
        "const btn = document.querySelector('#myBtn');\n"
        "const items = document.querySelectorAll('.item');\n"
        "```\n\n"
        "## Event Listeners\n"
        "```js\n"
        "btn.addEventListener('click', () => {\n"
        "  alert('Button clicked!');\n"
        "});\n"
        "```\n\n"
        "## Changing Content\n"
        "```js\n"
        "const heading = document.querySelector('h1');\n"
        "heading.textContent = 'Updated by JS!';\n"
        "heading.style.color = '#6366f1';\n"
        "```\n\n"
        "## Form Validation\n"
        "```js\n"
        "form.addEventListener('submit', (e) => {\n"
        "  if (!emailInput.value.includes('@')) {\n"
        "    e.preventDefault();\n"
        "    alert('Invalid email.');\n"
        "  }\n"
        "});\n"
        "```\n\n"
        "## Key Takeaways\n"
        "- `querySelector` selects the first match\n"
        "- `addEventListener` attaches event handlers\n"
        "- Use `e.preventDefault()` to stop default form submission"
    ),
    'Build a REST API with Django': (
        "## What is a REST API?\n"
        "A REST API lets your frontend communicate with your backend over HTTP using JSON.\n\n"
        "## Setup\n"
        "```bash\n"
        "pip install djangorestframework\n"
        "```\n"
        "Add `'rest_framework'` to `INSTALLED_APPS`.\n\n"
        "## Serializer\n"
        "```python\n"
        "from rest_framework import serializers\n"
        "from .models import Quest\n\n"
        "class QuestSerializer(serializers.ModelSerializer):\n"
        "    class Meta:\n"
        "        model = Quest\n"
        "        fields = ['id', 'title', 'xp_reward', 'difficulty']\n"
        "```\n\n"
        "## View\n"
        "```python\n"
        "from rest_framework.decorators import api_view\n"
        "from rest_framework.response import Response\n\n"
        "@api_view(['GET'])\n"
        "def quest_api(request):\n"
        "    quests = Quest.objects.all()\n"
        "    return Response(QuestSerializer(quests, many=True).data)\n"
        "```\n\n"
        "## Key Takeaways\n"
        "- Serializers convert models to JSON and back\n"
        "- Use `@api_view` for function-based endpoints\n"
        "- Test with Postman or the DRF browser interface"
    ),
    'Connect a database': (
        "## Django ORM Basics\n"
        "Django ORM lets you query the database with Python — no raw SQL needed.\n\n"
        "## Querying\n"
        "```python\n"
        "Quest.objects.all()\n"
        "Quest.objects.filter(difficulty='easy')\n"
        "Quest.objects.order_by('-xp_reward')\n"
        "get_object_or_404(Quest, id=1)\n"
        "```\n\n"
        "## Creating Records\n"
        "```python\n"
        "Quest.objects.create(title='New Quest', xp_reward=100, difficulty='easy')\n"
        "```\n\n"
        "## Relationships\n"
        "```python\n"
        "class CompletedQuest(models.Model):\n"
        "    user  = models.ForeignKey(User, on_delete=models.CASCADE)\n"
        "    quest = models.ForeignKey(Quest, on_delete=models.CASCADE)\n"
        "```\n\n"
        "## Key Takeaways\n"
        "- Always run `makemigrations` + `migrate` after model changes\n"
        "- Use `select_related` to avoid N+1 queries\n"
        "- `get_or_create` is great for upsert patterns"
    ),
    'Write unit tests': (
        "## Why Test?\n"
        "Tests catch bugs early and give you confidence when refactoring.\n\n"
        "## Django Test Client\n"
        "```python\n"
        "from django.test import TestCase, Client\n"
        "from django.contrib.auth.models import User\n\n"
        "class QuestTests(TestCase):\n"
        "    def setUp(self):\n"
        "        self.client = Client()\n"
        "        self.user = User.objects.create_user('tester', password='pass')\n\n"
        "    def test_dashboard_requires_login(self):\n"
        "        r = self.client.get('/dashboard/')\n"
        "        self.assertEqual(r.status_code, 302)\n\n"
        "    def test_dashboard_loads_when_logged_in(self):\n"
        "        self.client.login(username='tester', password='pass')\n"
        "        r = self.client.get('/dashboard/')\n"
        "        self.assertEqual(r.status_code, 200)\n"
        "```\n\n"
        "## Running Tests\n"
        "```bash\n"
        "python manage.py test\n"
        "```\n\n"
        "## Key Takeaways\n"
        "- `setUp` runs before every test method\n"
        "- Test both success and failure paths\n"
        "- Aim for high coverage on views and models"
    ),
    'Deploy to the cloud': (
        "## Deploying Django to Render\n\n"
        "## 1. Prepare settings\n"
        "```python\n"
        "DEBUG = False\n"
        "ALLOWED_HOSTS = ['your-app.onrender.com']\n"
        "STATIC_ROOT = BASE_DIR / 'staticfiles'\n"
        "```\n\n"
        "## 2. Install dependencies\n"
        "```bash\n"
        "pip install gunicorn whitenoise\n"
        "pip freeze > requirements.txt\n"
        "```\n\n"
        "## 3. Add WhiteNoise for static files\n"
        "```python\n"
        "MIDDLEWARE = [\n"
        "    'whitenoise.middleware.WhiteNoiseMiddleware',\n"
        "    ...\n"
        "]\n"
        "```\n\n"
        "## 4. Render start command\n"
        "```bash\n"
        "gunicorn questlearn.wsgi:application\n"
        "```\n\n"
        "## Key Takeaways\n"
        "- Never deploy with `DEBUG = True`\n"
        "- Use environment variables for `SECRET_KEY`\n"
        "- Run `collectstatic` before deploying"
    ),
    'Implement user authentication': (
        "## Django Auth System\n"
        "Django ships with a full auth system — users, passwords, sessions, permissions.\n\n"
        "## Login / Logout\n"
        "```python\n"
        "from django.contrib.auth import login, logout, authenticate\n\n"
        "def login_view(request):\n"
        "    user = authenticate(username=..., password=...)\n"
        "    if user:\n"
        "        login(request, user)\n"
        "        return redirect('dashboard')\n\n"
        "def logout_view(request):\n"
        "    logout(request)\n"
        "    return redirect('home')\n"
        "```\n\n"
        "## Protecting Views\n"
        "```python\n"
        "from django.contrib.auth.decorators import login_required\n\n"
        "@login_required\n"
        "def dashboard(request):\n"
        "    ...\n"
        "```\n\n"
        "## Custom User Form\n"
        "```python\n"
        "from django.contrib.auth.forms import UserCreationForm\n\n"
        "class SignupForm(UserCreationForm):\n"
        "    email = forms.EmailField(required=True)\n"
        "    class Meta:\n"
        "        model = User\n"
        "        fields = ['username', 'email', 'password1', 'password2']\n"
        "```\n\n"
        "## Key Takeaways\n"
        "- `@login_required` redirects unauthenticated users to `LOGIN_URL`\n"
        "- Always hash passwords — never store plain text\n"
        "- Use `request.user` to access the logged-in user"
    ),
}

updated = 0
for title, content in content_map.items():
    rows = Quest.objects.filter(title=title).update(content=content)
    updated += rows
    print(f'Updated: {title}')

print(f'\nDone. {updated} quests seeded with content.')
